python run_glue.py 
            --model_name_or_path xlm-roberta-base 
            --train_file  content/drive/My\ Drive/Colab\ Notebooks/NLP_Project/Data_/ROC/ROC_AF_ManPlts/AF_ManPlts_train.csv 
            --validation_file  content/drive/My\ Drive/Colab\ Notebooks/NLP_Project/Data_/ROC/ROC_AF_ManPlts/AF_ManPlts_valid.csv 
            --do_train 
            --do_eval 
            --max_seq_length 128 
            --per_device_train_batch_size 2 
            --learning_rate 2e-5 
            --num_train_epochs 2 
            --output_dir content/drive/My\ Drive/Colab\ Notebooks/NLP_Project/Data_/results 
            --task_name stsb